

// const serviceCategories = [
//   // ================= Home & Garden =================
//   {
//     id: "house-cleaning",
//     slug: "house-cleaning",
//     name: "House Cleaning",
//     category: "home-garden",
//     categoryLabel: "Home & Garden",
//     categoryBg: "bg-green-100",
//     pricingType: "fixed",
//     image: "https://images.unsplash.com/photo-1581579180926-8e25f5fc6e9c?w=800",
//     description: "Professional home cleaning services.",
//     isActive: true,
//     isFeatured: true,
//     questions: [
//       { type: "section", label: "Contact Information" },
//       { type: "text", label: "Full Name", key: "name", required: true },
//       { type: "email", label: "Email Address", key: "email" },
//       { type: "number", label: "Phone Number", key: "phone" },
//       { type: "section", label: "Cleaning Details" },
//       { type: "select", label: "Cleaning Type", key: "cleaningType", options: ["Standard", "Deep Cleaning", "Move Out/In"] },
//       { type: "number", label: "Area (Sq Ft)", key: "area" },
//       { type: "textarea", label: "Additional Instructions", key: "details" },
//       { type: "date", label: "Preferred Service Date", key: "date" }
//     ]
//   },
//   {
//     id: "plumbing",
//     slug: "plumbing",
//     name: "Plumbing",
//     category: "home-garden",
//     categoryLabel: "Home & Garden",
//     categoryBg: "bg-green-100",
//     pricingType: "fixed",
//     image: "https://images.unsplash.com/photo-1581090700227-1fc6d5cbe70e?w=800",
//     description: "Expert plumbing services for residential and commercial needs.",
//     isActive: true,
//     isFeatured: true,
//     questions: [
//       { type: "section", label: "Contact Information" },
//       { type: "text", label: "Full Name", key: "name", required: true },
//       { type: "email", label: "Email Address", key: "email" },
//       { type: "number", label: "Phone Number", key: "phone" },
//       { type: "section", label: "Plumbing Details" },
//       { type: "select", label: "Service Type", key: "serviceType", options: ["Leak Repair", "Pipe Installation", "Drain Cleaning", "Fixture Installation"] },
//       { type: "textarea", label: "Additional Instructions", key: "details" },
//       { type: "date", label: "Preferred Service Date", key: "date" }
//     ]
//   },
//   {
//     id: "electrician",
//     slug: "electrician",
//     name: "Electrician",
//     category: "home-garden",
//     categoryLabel: "Home & Garden",
//     categoryBg: "bg-green-100",
//     pricingType: "fixed",
//     image: "https://images.unsplash.com/photo-1600585154340-be6161f6a3c6?w=800",
//     description: "Certified electricians for installations, repairs, and maintenance.",
//     isActive: true,
//     isFeatured: true,
//     questions: [
//       { type: "section", label: "Contact Information" },
//       { type: "text", label: "Full Name", key: "name", required: true },
//       { type: "email", label: "Email Address", key: "email" },
//       { type: "number", label: "Phone Number", key: "phone" },
//       { type: "section", label: "Electrician Details" },
//       { type: "select", label: "Service Type", key: "serviceType", options: ["Wiring", "Lighting Installation", "Appliance Repair", "Electrical Safety Inspection"] },
//       { type: "textarea", label: "Additional Instructions", key: "details" },
//       { type: "date", label: "Preferred Service Date", key: "date" }
//     ]
//   },
//   {
//     id: "ac-repair",
//     slug: "ac-repair",
//     name: "AC Repair",
//     category: "home-garden",
//     categoryLabel: "Home & Garden",
//     categoryBg: "bg-green-100",
//     pricingType: "fixed",
//     image: "https://images.unsplash.com/photo-1591522816337-4b8fef920a9b?w=800",
//     description: "Reliable AC repair and maintenance services.",
//     isActive: true,
//     isFeatured: true,
//     questions: [
//       { type: "section", label: "Contact Information" },
//       { type: "text", label: "Full Name", key: "name", required: true },
//       { type: "email", label: "Email Address", key: "email" },
//       { type: "number", label: "Phone Number", key: "phone" },
//       { type: "section", label: "AC Repair Details" },
//       { type: "select", label: "AC Type", key: "acType", options: ["Window AC", "Split AC", "Central AC"] },
//       { type: "text", label: "Issue Description", key: "issue" },
//       { type: "date", label: "Preferred Service Date", key: "date" }
//     ]
//   },

//   // ================= Roof, Solar, Carpets =================
//   {
//     id: "roof-repair",
//     slug: "roof-repair",
//     name: "Roof Repair",
//     category: "home-garden",
//     categoryLabel: "Home & Garden",
//     categoryBg: "bg-green-100",
//     pricingType: "fixed",
//     image: "https://images.unsplash.com/photo-1581092795363-24c8c0a6b1c7?w=800",
//     description: "Professional roof repair services for any type of roofing.",
//     isActive: true,
//     isFeatured: true,
//     questions: [
//       { type: "section", label: "Contact Information" },
//       { type: "text", label: "Full Name", key: "name", required: true },
//       { type: "email", label: "Email Address", key: "email" },
//       { type: "number", label: "Phone Number", key: "phone" },
//       { type: "section", label: "Roof Repair Details" },
//       { type: "select", label: "Roof Type", key: "roofType", options: ["Shingle", "Metal", "Tile", "Flat"] },
//       { type: "text", label: "Issue Description", key: "issue" },
//       { type: "date", label: "Preferred Service Date", key: "date" }
//     ]
//   },
//   {
//     id: "solar-panel-installation",
//     slug: "solar-panel-installation",
//     name: "Solar Panel Installation",
//     category: "home-garden",
//     categoryLabel: "Home & Garden",
//     categoryBg: "bg-green-100",
//     pricingType: "fixed",
//     image: "https://images.unsplash.com/photo-1598514983684-4c1a38369fa8?w=800",
//     description: "Expert solar panel installation for residential and commercial properties.",
//     isActive: true,
//     isFeatured: true,
//     questions: [
//       { type: "section", label: "Contact Information" },
//       { type: "text", label: "Full Name", key: "name", required: true },
//       { type: "email", label: "Email Address", key: "email" },
//       { type: "number", label: "Phone Number", key: "phone" },
//       { type: "section", label: "Solar Installation Details" },
//       { type: "number", label: "System Size (kW)", key: "systemSize" },
//       { type: "text", label: "Roof Type", key: "roofType" },
//       { type: "textarea", label: "Additional Instructions", key: "details" },
//       { type: "date", label: "Preferred Service Date", key: "date" }
//     ]
//   },

//   // ================= Creative & Digital =================
//   {
//     id: "graphic-design",
//     slug: "graphic-design",
//     name: "Graphic Design",
//     category: "creative-digital",
//     categoryLabel: "Creative & Digital",
//     categoryBg: "bg-blue-100",
//     pricingType: "fixed",
//     image: "https://images.unsplash.com/photo-1506084868230-bb9d95c24759?w=800",
//     description: "Professional graphic design services for branding, marketing, and content.",
//     isActive: true,
//     isFeatured: true,
//     questions: [
//       { type: "section", label: "Contact Information" },
//       { type: "text", label: "Full Name", key: "name", required: true },
//       { type: "email", label: "Email Address", key: "email" },
//       { type: "number", label: "Phone Number", key: "phone" },
//       { type: "section", label: "Design Details" },
//       { type: "select", label: "Design Type", key: "designType", options: ["Logo", "Brochure", "Social Media", "Banner"] },
//       { type: "textarea", label: "Additional Instructions", key: "details" },
//       { type: "date", label: "Preferred Completion Date", key: "date" }
//     ]
//   },

//   {
//     id: "web-design",
//     slug: "web-design",
//     name: "Web Design",
//     category: "creative-digital",
//     categoryLabel: "Creative & Digital",
//     categoryBg: "bg-blue-100",
//     pricingType: "fixed",
//     image: "https://images.unsplash.com/photo-1498050108023-c5249f4df085?w=800",
//     description: "Custom website design services to enhance your online presence.",
//     isActive: true,
//     isFeatured: true,
//     questions: [
//       { type: "section", label: "Contact Information" },
//       { type: "text", label: "Full Name", key: "name", required: true },
//       { type: "email", label: "Email Address", key: "email" },
//       { type: "number", label: "Phone Number", key: "phone" },
//       { type: "section", label: "Website Design Details" },
//       { type: "select", label: "Website Type", key: "websiteType", options: ["Business", "Portfolio", "E-commerce", "Blog"] },
//       { type: "textarea", label: "Additional Instructions", key: "details" },
//       { type: "date", label: "Preferred Completion Date", key: "date" }
//     ]
//   },
//   // ================= Creative & Digital (continued) =================
// {
//   id: "web-development",
//   slug: "web-development",
//   name: "Web Development",
//   category: "creative-digital",
//   categoryLabel: "Creative & Digital",
//   categoryBg: "bg-blue-100",
//   pricingType: "fixed",
//   image: "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=800",
//   description: "Professional web development for custom websites and apps.",
//   isActive: true,
//   isFeatured: true,
//   questions: [
//     { type: "section", label: "Contact Information" },
//     { type: "text", label: "Full Name", key: "name", required: true },
//     { type: "email", label: "Email Address", key: "email" },
//     { type: "number", label: "Phone Number", key: "phone" },
//     { type: "section", label: "Development Details" },
//     { type: "select", label: "Platform", key: "platform", options: ["React", "Vue", "WordPress", "Custom"] },
//     { type: "textarea", label: "Project Requirements", key: "details" },
//     { type: "date", label: "Preferred Completion Date", key: "date" }
//   ]
// },
// {
//   id: "ui-ux-design",
//   slug: "ui-ux-design",
//   name: "UI/UX Design",
//   category: "creative-digital",
//   categoryLabel: "Creative & Digital",
//   categoryBg: "bg-blue-100",
//   pricingType: "fixed",
//   image: "https://images.unsplash.com/photo-1581091870622-08eb1cf5f7d5?w=800",
//   description: "User interface and experience design for websites and apps.",
//   isActive: true,
//   isFeatured: true,
//   questions: [
//     { type: "section", label: "Contact Information" },
//     { type: "text", label: "Full Name", key: "name", required: true },
//     { type: "email", label: "Email Address", key: "email" },
//     { type: "number", label: "Phone Number", key: "phone" },
//     { type: "section", label: "Design Details" },
//     { type: "select", label: "Project Type", key: "projectType", options: ["Website", "Mobile App", "Software", "Other"] },
//     { type: "textarea", label: "Design Requirements", key: "details" },
//     { type: "date", label: "Preferred Completion Date", key: "date" }
//   ]
// },
// {
//   id: "digital-marketing",
//   slug: "digital-marketing",
//   name: "Digital Marketing",
//   category: "creative-digital",
//   categoryLabel: "Creative & Digital",
//   categoryBg: "bg-blue-100",
//   pricingType: "fixed",
//   image: "https://images.unsplash.com/photo-1559526324-593bc073d938?w=800",
//   description: "Comprehensive digital marketing services to grow your business online.",
//   isActive: true,
//   isFeatured: true,
//   questions: [
//     { type: "section", label: "Contact Information" },
//     { type: "text", label: "Full Name", key: "name", required: true },
//     { type: "email", label: "Email Address", key: "email" },
//     { type: "number", label: "Phone Number", key: "phone" },
//     { type: "section", label: "Marketing Details" },
//     { type: "select", label: "Service Focus", key: "serviceFocus", options: ["SEO", "Social Media", "Email Marketing", "PPC Ads"] },
//     { type: "textarea", label: "Business Details & Goals", key: "details" },
//     { type: "date", label: "Preferred Start Date", key: "date" }
//   ]
// },
// {
//   id: "seo-services",
//   slug: "seo-services",
//   name: "SEO Services",
//   category: "creative-digital",
//   categoryLabel: "Creative & Digital",
//   categoryBg: "bg-blue-100",
//   pricingType: "fixed",
//   image: "https://images.unsplash.com/photo-1504384308090-c894fdcc538d?w=800",
//   description: "Search engine optimization to improve website visibility and ranking.",
//   isActive: true,
//   isFeatured: true,
//   questions: [
//     { type: "section", label: "Contact Information" },
//     { type: "text", label: "Full Name", key: "name", required: true },
//     { type: "email", label: "Email Address", key: "email" },
//     { type: "number", label: "Phone Number", key: "phone" },
//     { type: "section", label: "SEO Details" },
//     { type: "textarea", label: "Website URL", key: "websiteUrl" },
//     { type: "textarea", label: "Keywords / Goals", key: "keywords" },
//     { type: "date", label: "Preferred Start Date", key: "date" }
//   ]
// },
// {
//   id: "content-writing",
//   slug: "content-writing",
//   name: "Content Writing",
//   category: "creative-digital",
//   categoryLabel: "Creative & Digital",
//   categoryBg: "bg-blue-100",
//   pricingType: "fixed",
//   image: "https://images.unsplash.com/photo-1524995997946-a1c2e315a42f?w=800",
//   description: "High-quality content writing for websites, blogs, and marketing materials.",
//   isActive: true,
//   isFeatured: true,
//   questions: [
//     { type: "section", label: "Contact Information" },
//     { type: "text", label: "Full Name", key: "name", required: true },
//     { type: "email", label: "Email Address", key: "email" },
//     { type: "number", label: "Phone Number", key: "phone" },
//     { type: "section", label: "Content Details" },
//     { type: "select", label: "Content Type", key: "contentType", options: ["Blog Post", "Article", "Website Copy", "Social Media"] },
//     { type: "textarea", label: "Topic / Instructions", key: "details" },
//     { type: "date", label: "Preferred Delivery Date", key: "date" }
//   ]
// },
// {
//   id: "copywriting",
//   slug: "copywriting",
//   name: "Copywriting",
//   category: "creative-digital",
//   categoryLabel: "Creative & Digital",
//   categoryBg: "bg-blue-100",
//   pricingType: "fixed",
//   image: "https://images.unsplash.com/photo-1581091870622-08eb1cf5f7d5?w=800",
//   description: "Professional copywriting for ads, sales pages, and marketing campaigns.",
//   isActive: true,
//   isFeatured: true,
//   questions: [
//     { type: "section", label: "Contact Information" },
//     { type: "text", label: "Full Name", key: "name", required: true },
//     { type: "email", label: "Email Address", key: "email" },
//     { type: "number", label: "Phone Number", key: "phone" },
//     { type: "section", label: "Copywriting Details" },
//     { type: "textarea", label: "Project / Product Details", key: "details" },
//     { type: "select", label: "Copy Type", key: "copyType", options: ["Ad Copy", "Sales Page", "Email Sequence", "Landing Page"] },
//     { type: "date", label: "Preferred Delivery Date", key: "date" }
//   ]
// },
// {
//   id: "app-development",
//   slug: "app-development",
//   name: "App Development",
//   category: "creative-digital",
//   categoryLabel: "Creative & Digital",
//   categoryBg: "bg-blue-100",
//   pricingType: "fixed",
//   image: "https://images.unsplash.com/photo-1523475496153-3b2bff8b5c47?w=800",
//   description: "Custom mobile app development for Android and iOS platforms.",
//   isActive: true,
//   isFeatured: true,
//   questions: [
//     { type: "section", label: "Contact Information" },
//     { type: "text", label: "Full Name", key: "name", required: true },
//     { type: "email", label: "Email Address", key: "email" },
//     { type: "number", label: "Phone Number", key: "phone" },
//     { type: "section", label: "App Development Details" },
//     { type: "select", label: "Platform", key: "platform", options: ["Android", "iOS", "Both"] },
//     { type: "textarea", label: "App Features / Instructions", key: "details" },
//     { type: "date", label: "Preferred Launch Date", key: "date" }
//   ]
// },
// {
//   id: "photography",
//   slug: "photography",
//   name: "Photography",
//   category: "creative-digital",
//   categoryLabel: "Creative & Digital",
//   categoryBg: "bg-blue-100",
//   pricingType: "fixed",
//   image: "https://images.unsplash.com/photo-1519183071298-a2962e20e3be?w=800",
//   description: "Professional photography services for events, portraits, and products.",
//   isActive: true,
//   isFeatured: true,
//   questions: [
//     { type: "section", label: "Contact Information" },
//     { type: "text", label: "Full Name", key: "name", required: true },
//     { type: "email", label: "Email Address", key: "email" },
//     { type: "number", label: "Phone Number", key: "phone" },
//     { type: "section", label: "Photography Details" },
//     { type: "select", label: "Photography Type", key: "photoType", options: ["Event", "Portrait", "Product", "Wedding"] },
//     { type: "textarea", label: "Additional Instructions", key: "details" },
//     { type: "date", label: "Preferred Date", key: "date" }
//   ]
// },
// {
//   id: "video-editing",
//   slug: "video-editing",
//   name: "Video Editing",
//   category: "creative-digital",
//   categoryLabel: "Creative & Digital",
//   categoryBg: "bg-blue-100",
//   pricingType: "fixed",
//   image: "https://images.unsplash.com/photo-1589394813485-d51f847b5b8f?w=800",
//   description: "Professional video editing for personal and business projects.",
//   isActive: true,
//   isFeatured: true,
//   questions: [
//     { type: "section", label: "Contact Information" },
//     { type: "text", label: "Full Name", key: "name", required: true },
//     { type: "email", label: "Email Address", key: "email" },
//     { type: "number", label: "Phone Number", key: "phone" },
//     { type: "section", label: "Video Editing Details" },
//     { type: "textarea", label: "Video Type / Instructions", key: "details" },
//     { type: "select", label: "Editing Style", key: "editingStyle", options: ["Corporate", "Social Media", "Event Highlights", "Creative"] },
//     { type: "date", label: "Preferred Delivery Date", key: "date" }
//   ]
// },
// // ================= Health & Wellness =================
// {
//   id: "personal-trainer",
//   slug: "personal-trainer",
//   name: "Personal Trainer",
//   category: "health-wellness",
//   categoryLabel: "Health & Wellness",
//   categoryBg: "bg-yellow-100",
//   pricingType: "fixed",
//   image: "https://images.unsplash.com/photo-1599058917210-5b7e121124fa?w=800",
//   description: "Professional personal training to help you reach your fitness goals.",
//   isActive: true,
//   isFeatured: true,
//   questions: [
//     { type: "section", label: "Contact Information" },
//     { type: "text", label: "Full Name", key: "name", required: true },
//     { type: "email", label: "Email Address", key: "email" },
//     { type: "number", label: "Phone Number", key: "phone" },
//     { type: "section", label: "Training Details" },
//     { type: "select", label: "Training Type", key: "trainingType", options: ["Strength", "Cardio", "Flexibility", "Weight Loss"] },
//     { type: "number", label: "Sessions per Week", key: "sessions" },
//     { type: "textarea", label: "Additional Instructions / Goals", key: "details" },
//     { type: "date", label: "Preferred Start Date", key: "date" }
//   ]
// },
// {
//   id: "nutritionist-consultation",
//   slug: "nutritionist-consultation",
//   name: "Nutritionist Consultation",
//   category: "health-wellness",
//   categoryLabel: "Health & Wellness",
//   categoryBg: "bg-yellow-100",
//   pricingType: "fixed",
//   image: "https://images.unsplash.com/photo-1556912990-30d2b1b1095c?w=800",
//   description: "Personalized nutrition advice for health and wellness.",
//   isActive: true,
//   isFeatured: true,
//   questions: [
//     { type: "section", label: "Contact Information" },
//     { type: "text", label: "Full Name", key: "name", required: true },
//     { type: "email", label: "Email Address", key: "email" },
//     { type: "number", label: "Phone Number", key: "phone" },
//     { type: "section", label: "Consultation Details" },
//     { type: "textarea", label: "Health Goals / Diet Preferences", key: "details" },
//     { type: "date", label: "Preferred Consultation Date", key: "date" }
//   ]
// },
// {
//   id: "yoga-instructor",
//   slug: "yoga-instructor",
//   name: "Yoga Instructor",
//   category: "health-wellness",
//   categoryLabel: "Health & Wellness",
//   categoryBg: "bg-yellow-100",
//   pricingType: "fixed",
//   image: "https://images.unsplash.com/photo-1554394872-bb9d62a2a350?w=800",
//   description: "Professional yoga instruction for wellness and flexibility.",
//   isActive: true,
//   isFeatured: true,
//   questions: [
//     { type: "section", label: "Contact Information" },
//     { type: "text", label: "Full Name", key: "name", required: true },
//     { type: "email", label: "Email Address", key: "email" },
//     { type: "number", label: "Phone Number", key: "phone" },
//     { type: "section", label: "Yoga Details" },
//     { type: "select", label: "Yoga Type", key: "yogaType", options: ["Hatha", "Vinyasa", "Ashtanga", "Meditation"] },
//     { type: "textarea", label: "Health Goals / Experience Level", key: "details" },
//     { type: "date", label: "Preferred Start Date", key: "date" }
//   ]
// },
// {
//   id: "physiotherapy",
//   slug: "physiotherapy",
//   name: "Physiotherapy",
//   category: "health-wellness",
//   categoryLabel: "Health & Wellness",
//   categoryBg: "bg-yellow-100",
//   pricingType: "fixed",
//   image: "https://images.unsplash.com/photo-1588776814546-3e9b44b3d7f4?w=800",
//   description: "Professional physiotherapy services for injury recovery and mobility.",
//   isActive: true,
//   isFeatured: true,
//   questions: [
//     { type: "section", label: "Contact Information" },
//     { type: "text", label: "Full Name", key: "name", required: true },
//     { type: "email", label: "Email Address", key: "email" },
//     { type: "number", label: "Phone Number", key: "phone" },
//     { type: "section", label: "Physiotherapy Details" },
//     { type: "textarea", label: "Injury / Problem Description", key: "details" },
//     { type: "select", label: "Treatment Type", key: "treatmentType", options: ["Rehabilitation", "Pain Management", "Post-Surgery Therapy"] },
//     { type: "date", label: "Preferred Appointment Date", key: "date" }
//   ]
// },
// {
//   id: "mental-health-coaching",
//   slug: "mental-health-coaching",
//   name: "Mental Health Coaching",
//   category: "health-wellness",
//   categoryLabel: "Health & Wellness",
//   categoryBg: "bg-yellow-100",
//   pricingType: "fixed",
//   image: "https://images.unsplash.com/photo-1523292564010-31b8d40c7e7d?w=800",
//   description: "Professional mental health coaching and counseling services.",
//   isActive: true,
//   isFeatured: true,
//   questions: [
//     { type: "section", label: "Contact Information" },
//     { type: "text", label: "Full Name", key: "name", required: true },
//     { type: "email", label: "Email Address", key: "email" },
//     { type: "number", label: "Phone Number", key: "phone" },
//     { type: "section", label: "Coaching Details" },
//     { type: "textarea", label: "Challenges / Goals", key: "details" },
//     { type: "date", label: "Preferred Session Date", key: "date" }
//   ]
// },
// {
//   id: "diet-meal-planning",
//   slug: "diet-meal-planning",
//   name: "Diet Meal Planning",
//   category: "health-wellness",
//   categoryLabel: "Health & Wellness",
//   categoryBg: "bg-yellow-100",
//   pricingType: "fixed",
//   image: "https://images.unsplash.com/photo-1587397891524-0f6f5d9e2b2b?w=800",
//   description: "Customized diet and meal planning for health and fitness goals.",
//   isActive: true,
//   isFeatured: true,
//   questions: [
//     { type: "section", label: "Contact Information" },
//     { type: "text", label: "Full Name", key: "name", required: true },
//     { type: "email", label: "Email Address", key: "email" },
//     { type: "number", label: "Phone Number", key: "phone" },
//     { type: "section", label: "Diet Planning Details" },
//     { type: "textarea", label: "Health Goals / Preferences", key: "details" },
//     { type: "select", label: "Diet Type", key: "dietType", options: ["Vegetarian", "Vegan", "Keto", "Balanced"] },
//     { type: "date", label: "Preferred Start Date", key: "date" }
//   ]
// },
// {
//   id: "massage-therapy",
//   slug: "massage-therapy",
//   name: "Massage Therapy",
//   category: "health-wellness",
//   categoryLabel: "Health & Wellness",
//   categoryBg: "bg-yellow-100",
//   pricingType: "fixed",
//   image: "https://images.unsplash.com/photo-1598363519215-5c5ee1be9e4f?w=800",
//   description: "Professional massage therapy for relaxation and pain relief.",
//   isActive: true,
//   isFeatured: true,
//   questions: [
//     { type: "section", label: "Contact Information" },
//     { type: "text", label: "Full Name", key: "name", required: true },
//     { type: "email", label: "Email Address", key: "email" },
//     { type: "number", label: "Phone Number", key: "phone" },
//     { type: "section", label: "Massage Details" },
//     { type: "select", label: "Massage Type", key: "massageType", options: ["Swedish", "Deep Tissue", "Sports", "Aromatherapy"] },
//     { type: "textarea", label: "Additional Instructions", key: "details" },
//     { type: "date", label: "Preferred Appointment Date", key: "date" }
//   ]
// },
// {
//   id: "pilates-instruction",
//   slug: "pilates-instruction",
//   name: "Pilates Instruction",
//   category: "health-wellness",
//   categoryLabel: "Health & Wellness",
//   categoryBg: "bg-yellow-100",
//   pricingType: "fixed",
//   image: "https://images.unsplash.com/photo-1594737625785-d31cf7e4c245?w=800",
//   description: "Personalized Pilates sessions to improve strength, flexibility, and posture.",
//   isActive: true,
//   isFeatured: true,
//   questions: [
//     { type: "section", label: "Contact Information" },
//     { type: "text", label: "Full Name", key: "name", required: true },
//     { type: "email", label: "Email Address", key: "email" },
//     { type: "number", label: "Phone Number", key: "phone" },
//     { type: "section", label: "Pilates Details" },
//     { type: "select", label: "Experience Level", key: "experienceLevel", options: ["Beginner", "Intermediate", "Advanced"] },
//     { type: "number", label: "Sessions per Week", key: "sessions" },
//     { type: "textarea", label: "Additional Goals / Instructions", key: "details" },
//     { type: "date", label: "Preferred Start Date", key: "date" }
//   ]
// },
// {
//   id: "dj-services",
//   slug: "dj-services",
//   name: "DJ Services",
//   category: "entertainment-lifestyle",
//   categoryLabel: "Entertainment & Lifestyle",
//   categoryBg: "bg-pink-100",
//   pricingType: "fixed",
//   image: "https://images.unsplash.com/photo-1552425436-fd80c4d278bb?w=800",
//   description: "Professional DJ services for parties, events, and weddings.",
//   isActive: true,
//   isFeatured: true,
//   questions: [
//     { type: "section", label: "Contact Information" },
//     { type: "text", label: "Full Name", key: "name", required: true },
//     { type: "email", label: "Email Address", key: "email" },
//     { type: "number", label: "Phone Number", key: "phone" },
//     { type: "section", label: "Event Details" },
//     { type: "select", label: "Event Type", key: "eventType", options: ["Wedding", "Party", "Corporate", "Other"] },
//     { type: "textarea", label: "Additional Instructions", key: "details" },
//     { type: "date", label: "Event Date", key: "date" }
//   ]
// },
// {
//   id: "makeup-artist",
//   slug: "makeup-artist",
//   name: "Makeup Artist",
//   category: "entertainment-lifestyle",
//   categoryLabel: "Entertainment & Lifestyle",
//   categoryBg: "bg-pink-100",
//   pricingType: "fixed",
//   image: "https://images.unsplash.com/photo-1583947322767-cf8e1e8f9028?w=800",
//   description: "Professional makeup services for weddings, events, and photoshoots.",
//   isActive: true,
//   isFeatured: true,
//   questions: [
//     { type: "section", label: "Contact Information" },
//     { type: "text", label: "Full Name", key: "name", required: true },
//     { type: "email", label: "Email Address", key: "email" },
//     { type: "number", label: "Phone Number", key: "phone" },
//     { type: "section", label: "Makeup Details" },
//     { type: "select", label: "Occasion", key: "occasion", options: ["Wedding", "Event", "Photoshoot"] },
//     { type: "textarea", label: "Additional Preferences / Instructions", key: "details" },
//     { type: "date", label: "Preferred Date", key: "date" }
//   ]
// },
// {
//   id: "dance-instructor",
//   slug: "dance-instructor",
//   name: "Dance Instructor",
//   category: "entertainment-lifestyle",
//   categoryLabel: "Entertainment & Lifestyle",
//   categoryBg: "bg-pink-100",
//   pricingType: "fixed",
//   image: "https://images.unsplash.com/photo-1605902711622-cfb43c44331b?w=800",
//   description: "Private or group dance lessons for all skill levels.",
//   isActive: true,
//   isFeatured: true,
//   questions: [
//     { type: "section", label: "Contact Information" },
//     { type: "text", label: "Full Name", key: "name", required: true },
//     { type: "email", label: "Email Address", key: "email" },
//     { type: "number", label: "Phone Number", key: "phone" },
//     { type: "section", label: "Dance Details" },
//     { type: "select", label: "Dance Style", key: "danceStyle", options: ["Hip-Hop", "Ballet", "Salsa", "Contemporary"] },
//     { type: "number", label: "Sessions per Week", key: "sessions" },
//     { type: "textarea", label: "Additional Instructions / Goals", key: "details" },
//     { type: "date", label: "Preferred Start Date", key: "date" }
//   ]
// },
// {
//   id: "martial-arts-training",
//   slug: "martial-arts-training",
//   name: "Martial Arts Training",
//   category: "entertainment-lifestyle",
//   categoryLabel: "Entertainment & Lifestyle",
//   categoryBg: "bg-pink-100",
//   pricingType: "fixed",
//   image: "https://images.unsplash.com/photo-1599058915460-c9fc1b0d7b15?w=800",
//   description: "Professional martial arts instruction for self-defense and fitness.",
//   isActive: true,
//   isFeatured: true,
//   questions: [
//     { type: "section", label: "Contact Information" },
//     { type: "text", label: "Full Name", key: "name", required: true },
//     { type: "email", label: "Email Address", key: "email" },
//     { type: "number", label: "Phone Number", key: "phone" },
//     { type: "section", label: "Training Details" },
//     { type: "select", label: "Martial Art Style", key: "style", options: ["Karate", "Taekwondo", "Judo", "Kung Fu"] },
//     { type: "number", label: "Sessions per Week", key: "sessions" },
//     { type: "textarea", label: "Additional Goals / Instructions", key: "details" },
//     { type: "date", label: "Preferred Start Date", key: "date" }
//   ]
// },
// {
//   id: "event-planning",
//   slug: "event-planning",
//   name: "Event Planning",
//   category: "entertainment-lifestyle",
//   categoryLabel: "Entertainment & Lifestyle",
//   categoryBg: "bg-pink-100",
//   pricingType: "fixed",
//   image: "https://images.unsplash.com/photo-1518606370930-08363c2a8b6e?w=800",
//   description: "Professional event planning services for weddings, parties, and corporate events.",
//   isActive: true,
//   isFeatured: true,
//   questions: [
//     { type: "section", label: "Contact Information" },
//     { type: "text", label: "Full Name", key: "name", required: true },
//     { type: "email", label: "Email Address", key: "email" },
//     { type: "number", label: "Phone Number", key: "phone" },
//     { type: "section", label: "Event Details" },
//     { type: "select", label: "Event Type", key: "eventType", options: ["Wedding", "Party", "Corporate", "Other"] },
//     { type: "textarea", label: "Event Requirements / Notes", key: "details" },
//     { type: "date", label: "Event Date", key: "date" }
//   ]
// },
// {
//   id: "music-lessons",
//   slug: "music-lessons",
//   name: "Music Lessons",
//   category: "entertainment-lifestyle",
//   categoryLabel: "Entertainment & Lifestyle",
//   categoryBg: "bg-pink-100",
//   pricingType: "fixed",
//   image: "https://images.unsplash.com/photo-1511376777868-611b54f68947?w=800",
//   description: "Personalized music lessons for instruments and voice.",
//   isActive: true,
//   isFeatured: true,
//   questions: [
//     { type: "section", label: "Contact Information" },
//     { type: "text", label: "Full Name", key: "name", required: true },
//     { type: "email", label: "Email Address", key: "email" },
//     { type: "number", label: "Phone Number", key: "phone" },
//     { type: "section", label: "Lesson Details" },
//     { type: "select", label: "Instrument / Voice Type", key: "instrumentType", options: ["Piano", "Guitar", "Violin", "Voice"] },
//     { type: "number", label: "Sessions per Week", key: "sessions" },
//     { type: "textarea", label: "Additional Goals / Instructions", key: "details" },
//     { type: "date", label: "Preferred Start Date", key: "date" }
//   ]
// },
// {
//   id: "voice-coaching",
//   slug: "voice-coaching",
//   name: "Voice Coaching",
//   category: "entertainment-lifestyle",
//   categoryLabel: "Entertainment & Lifestyle",
//   categoryBg: "bg-pink-100",
//   pricingType: "fixed",
//   image: "https://images.unsplash.com/photo-1584697964151-0d6f8b69c924?w=800",
//   description: "Professional voice coaching for singing, public speaking, and performance.",
//   isActive: true,
//   isFeatured: true,
//   questions: [
//     { type: "section", label: "Contact Information" },
//     { type: "text", label: "Full Name", key: "name", required: true },
//     { type: "email", label: "Email Address", key: "email" },
//     { type: "number", label: "Phone Number", key: "phone" },
//     { type: "section", label: "Coaching Details" },
//     { type: "select", label: "Coaching Focus", key: "focus", options: ["Singing", "Speech", "Performance"] },
//     { type: "textarea", label: "Additional Goals / Instructions", key: "details" },
//     { type: "date", label: "Preferred Start Date", key: "date" }
//   ]
// },
// {
//   id: "party-wedding-photography",
//   slug: "party-wedding-photography",
//   name: "Party & Wedding Photography",
//   category: "entertainment-lifestyle",
//   categoryLabel: "Entertainment & Lifestyle",
//   categoryBg: "bg-pink-100",
//   pricingType: "fixed",
//   image: "https://images.unsplash.com/photo-1511206493939-712b5c0c5f98?w=800",
//   description: "Professional photography for parties, weddings, and special events.",
//   isActive: true,
//   isFeatured: true,
//   questions: [
//     { type: "section", label: "Contact Information" },
//     { type: "text", label: "Full Name", key: "name", required: true },
//     { type: "email", label: "Email Address", key: "email" },
//     { type: "number", label: "Phone Number", key: "phone" },
//     { type: "section", label: "Photography Details" },
//     { type: "textarea", label: "Event Details / Requirements", key: "details" },
//     { type: "date", label: "Event Date", key: "date" }
//   ]
// },
// {
//   id: "interior-styling",
//   slug: "interior-styling",
//   name: "Interior Styling",
//   category: "entertainment-lifestyle",
//   categoryLabel: "Entertainment & Lifestyle",
//   categoryBg: "bg-pink-100",
//   pricingType: "fixed",
//   image: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800",
//   description: "Professional interior styling and home decor services.",
//   isActive: true,
//   isFeatured: true,
//   questions: [
//     { type: "section", label: "Contact Information" },
//     { type: "text", label: "Full Name", key: "name", required: true },
//     { type: "email", label: "Email Address", key: "email" },
//     { type: "number", label: "Phone Number", key: "phone" },
//     { type: "section", label: "Styling Details" },
//     { type: "textarea", label: "Room / Space Details", key: "details" },
//     { type: "select", label: "Styling Focus", key: "focus", options: ["Living Room", "Bedroom", "Office", "Full Home"] },
//     { type: "date", label: "Preferred Styling Date", key: "date" }
//   ]
// },
// {
//   id: "personal-shopping",
//   slug: "personal-shopping",
//   name: "Personal Shopping",
//   category: "entertainment-lifestyle",
//   categoryLabel: "Entertainment & Lifestyle",
//   categoryBg: "bg-pink-100",
//   pricingType: "fixed",
//   image: "https://images.unsplash.com/photo-1542831371-d531d36971e6?w=800",
//   description: "Personal shopping services to help you select clothing, gifts, and lifestyle products.",
//   isActive: true,
//   isFeatured: true,
//   questions: [
//     { type: "section", label: "Contact Information" },
//     { type: "text", label: "Full Name", key: "name", required: true },
//     { type: "email", label: "Email Address", key: "email" },
//     { type: "number", label: "Phone Number", key: "phone" },
//     { type: "section", label: "Shopping Details" },
//     { type: "textarea", label: "Items / Preferences", key: "details" },
//     { type: "date", label: "Preferred Shopping Date", key: "date" }
//   ]
// },
// // ================= Business & Office Services =================
// {
//   id: "data-entry",
//   slug: "data-entry",
//   name: "Data Entry",
//   category: "business-office",
//   categoryLabel: "Business & Office",
//   categoryBg: "bg-purple-100",
//   pricingType: "fixed",
//   image: "https://images.unsplash.com/photo-1581091215364-1c8d0a6bfa86?w=800",
//   description: "Professional data entry services for businesses, documents, and spreadsheets.",
//   isActive: true,
//   isFeatured: true,
//   questions: [
//     { type: "section", label: "Contact Information" },
//     { type: "text", label: "Full Name", key: "name", required: true },
//     { type: "email", label: "Email Address", key: "email" },
//     { type: "number", label: "Phone Number", key: "phone" },
//     { type: "section", label: "Project Details" },
//     { type: "textarea", label: "Data Entry Instructions / Details", key: "details" },
//     { type: "number", label: "Number of Entries", key: "entries" },
//     { type: "date", label: "Preferred Completion Date", key: "date" }
//   ]
// },
// {
//   id: "virtual-assistant",
//   slug: "virtual-assistant",
//   name: "Virtual Assistant",
//   category: "business-office",
//   categoryLabel: "Business & Office",
//   categoryBg: "bg-purple-100",
//   pricingType: "fixed",
//   image: "https://images.unsplash.com/photo-1560250097-0b93528c311a?w=800",
//   description: "Professional virtual assistant services for business management and support.",
//   isActive: true,
//   isFeatured: true,
//   questions: [
//     { type: "section", label: "Contact Information" },
//     { type: "text", label: "Full Name", key: "name", required: true },
//     { type: "email", label: "Email Address", key: "email" },
//     { type: "number", label: "Phone Number", key: "phone" },
//     { type: "section", label: "Task Details" },
//     { type: "textarea", label: "Tasks / Instructions", key: "details" },
//     { type: "date", label: "Preferred Start Date", key: "date" }
//   ]
// },
// {
//   id: "social-media-management",
//   slug: "social-media-management",
//   name: "Social Media Management",
//   category: "business-office",
//   categoryLabel: "Business & Office",
//   categoryBg: "bg-purple-100",
//   pricingType: "fixed",
//   image: "https://images.unsplash.com/photo-1515378791036-0648a3ef77b2?w=800",
//   description: "Manage your social media accounts professionally to boost engagement and growth.",
//   isActive: true,
//   isFeatured: true,
//   questions: [
//     { type: "section", label: "Contact Information" },
//     { type: "text", label: "Full Name", key: "name", required: true },
//     { type: "email", label: "Email Address", key: "email" },
//     { type: "number", label: "Phone Number", key: "phone" },
//     { type: "section", label: "Management Details" },
//     { type: "textarea", label: "Platform / Goals / Instructions", key: "details" },
//     { type: "date", label: "Preferred Start Date", key: "date" }
//   ]
// },
// {
//   id: "ui-ux-design",
//   slug: "ui-ux-design",
//   name: "UI/UX Design",
//   category: "creative-digital",
//   categoryLabel: "Creative & Digital",
//   categoryBg: "bg-blue-100",
//   pricingType: "fixed",
//   image: "https://images.unsplash.com/photo-1581090700227-1b6f273d07e2?w=800",
//   description: "Professional UI/UX design services for websites and mobile applications.",
//   isActive: true,
//   isFeatured: true,
//   questions: [
//     { type: "section", label: "Contact Information" },
//     { type: "text", label: "Full Name", key: "name", required: true },
//     { type: "email", label: "Email Address", key: "email" },
//     { type: "number", label: "Phone Number", key: "phone" },
//     { type: "section", label: "Design Details" },
//     { type: "textarea", label: "Project Requirements / Instructions", key: "details" },
//     { type: "select", label: "Platform", key: "platform", options: ["Website", "Mobile App", "Other"] },
//     { type: "date", label: "Preferred Delivery Date", key: "date" }
//   ]
// },
// {
//   id: "resume-writing",
//   slug: "resume-writing",
//   name: "Resume Writing",
//   category: "business-office",
//   categoryLabel: "Business & Office",
//   categoryBg: "bg-purple-100",
//   pricingType: "fixed",
//   image: "https://images.unsplash.com/photo-1581091012184-1234b563d7d0?w=800",
//   description: "Professional resume and CV writing services to help you land your dream job.",
//   isActive: true,
//   isFeatured: true,
//   questions: [
//     { type: "section", label: "Contact Information" },
//     { type: "text", label: "Full Name", key: "name", required: true },
//     { type: "email", label: "Email Address", key: "email" },
//     { type: "number", label: "Phone Number", key: "phone" },
//     { type: "section", label: "Resume Details" },
//     { type: "textarea", label: "Current Resume / Experience Details", key: "details" },
//     { type: "select", label: "Industry / Role", key: "industry", options: ["IT", "Marketing", "Finance", "Healthcare", "Other"] },
//     { type: "date", label: "Preferred Delivery Date", key: "date" }
//   ]
// },
// {
//   id: "copywriting",
//   slug: "copywriting",
//   name: "Copywriting",
//   category: "creative-digital",
//   categoryLabel: "Creative & Digital",
//   categoryBg: "bg-blue-100",
//   pricingType: "fixed",
//   image: "https://images.unsplash.com/photo-1560264356-0c9f7a0a0c29?w=800",
//   description: "Professional copywriting services for websites, ads, and marketing materials.",
//   isActive: true,
//   isFeatured: true,
//   questions: [
//     { type: "section", label: "Contact Information" },
//     { type: "text", label: "Full Name", key: "name", required: true },
//     { type: "email", label: "Email Address", key: "email" },
//     { type: "number", label: "Phone Number", key: "phone" },
//     { type: "section", label: "Copywriting Details" },
//     { type: "textarea", label: "Project Details / Requirements", key: "details" },
//     { type: "select", label: "Type of Copy", key: "copyType", options: ["Website", "Advertisement", "Social Media", "Brochure"] },
//     { type: "date", label: "Preferred Delivery Date", key: "date" }
//   ]
// },
// {
//   id: "animation-motion-graphics",
//   slug: "animation-motion-graphics",
//   name: "Animation & Motion Graphics",
//   category: "creative-digital",
//   categoryLabel: "Creative & Digital",
//   categoryBg: "bg-blue-100",
//   pricingType: "fixed",
//   image: "https://images.unsplash.com/photo-1518770660439-4636190af475?w=800",
//   description: "Professional animation and motion graphics services for videos, ads, and presentations.",
//   isActive: true,
//   isFeatured: true,
//   questions: [
//     { type: "section", label: "Contact Information" },
//     { type: "text", label: "Full Name", key: "name", required: true },
//     { type: "email", label: "Email Address", key: "email" },
//     { type: "number", label: "Phone Number", key: "phone" },
//     { type: "section", label: "Animation Details" },
//     { type: "textarea", label: "Project Requirements / Instructions", key: "details" },
//     { type: "select", label: "Animation Type", key: "animationType", options: ["2D", "3D", "Motion Graphics"] },
//     { type: "date", label: "Preferred Delivery Date", key: "date" }
//   ]
// },
// // ================= Home & Garden / Repairs / Solar =================
// {
//   id: "ac-repair",
//   slug: "ac-repair",
//   name: "AC Repair",
//   category: "home-garden",
//   categoryLabel: "Home & Garden",
//   categoryBg: "bg-green-100",
//   pricingType: "fixed",
//   image: "https://images.unsplash.com/photo-1584467735871-8a30bb0e0735?auto=format&fit=crop&w=800&q=80",
//   description: "Professional AC repair and maintenance services for home and office.",
//   isActive: true,
//   isFeatured: true,
//   questions: [
//     { type: "section", label: "Contact Information" },
//     { type: "text", label: "Full Name", key: "name", required: true },
//     { type: "email", label: "Email Address", key: "email" },
//     { type: "number", label: "Phone Number", key: "phone" },
//     { type: "section", label: "AC Details" },
//     { type: "text", label: "AC Brand / Model", key: "acModel" },
//     { type: "select", label: "Issue Type", key: "issueType", options: ["Not Cooling", "Leakage", "Noise", "Other"] },
//     { type: "textarea", label: "Additional Instructions", key: "details" },
//     { type: "date", label: "Preferred Service Date", key: "date" }
//   ]
// },
// {
//   id: "roof-repair",
//   slug: "roof-repair",
//   name: "Roof Repair",
//   category: "home-garden",
//   categoryLabel: "Home & Garden",
//   categoryBg: "bg-green-100",
//   pricingType: "fixed",
//   image: "https://images.unsplash.com/photo-1601907228587-c76f09899e36?auto=format&fit=crop&w=800&q=80",
//   description: "Professional roof repair and maintenance for residential and commercial properties.",
//   isActive: true,
//   isFeatured: true,
//   questions: [
//     { type: "section", label: "Contact Information" },
//     { type: "text", label: "Full Name", key: "name", required: true },
//     { type: "email", label: "Email Address", key: "email" },
//     { type: "number", label: "Phone Number", key: "phone" },
//     { type: "section", label: "Roof Details" },
//     { type: "select", label: "Roof Material", key: "roofMaterial", options: ["Tile", "Metal", "Shingle", "Other"] },
//     { type: "textarea", label: "Issue Description / Instructions", key: "details" },
//     { type: "date", label: "Preferred Service Date", key: "date" }
//   ]
// },
// {
//   id: "solar-panel-installation",
//   slug: "solar-panel-installation",
//   name: "Solar Panel Installation",
//   category: "home-garden",
//   categoryLabel: "Home & Garden",
//   categoryBg: "bg-green-100",
//   pricingType: "fixed",
//   image: "https://images.unsplash.com/photo-1581090700227-1b6f273d07e2?auto=format&fit=crop&w=800&q=80",
//   description: "Professional solar panel installation for homes and businesses.",
//   isActive: true,
//   isFeatured: true,
//   questions: [
//     { type: "section", label: "Contact Information" },
//     { type: "text", label: "Full Name", key: "name", required: true },
//     { type: "email", label: "Email Address", key: "email" },
//     { type: "number", label: "Phone Number", key: "phone" },
//     { type: "section", label: "Installation Details" },
//     { type: "select", label: "Property Type", key: "propertyType", options: ["Residential", "Commercial"] },
//     { type: "number", label: "Number of Panels", key: "numPanels" },
//     { type: "textarea", label: "Additional Instructions", key: "details" },
//     { type: "date", label: "Preferred Installation Date", key: "date" }
//   ]
// },
// {
//   id: "plumbing",
//   slug: "plumbing",
//   name: "Plumbing",
//   category: "home-garden",
//   categoryLabel: "Home & Garden",
//   categoryBg: "bg-green-100",
//   pricingType: "fixed",
//   image: "https://images.unsplash.com/photo-1581090466329-0cc07241c0bb?auto=format&fit=crop&w=800&q=80",
//   description: "Professional plumbing services for repair, maintenance, and installation.",
//   isActive: true,
//   isFeatured: true,
//   questions: [
//     { type: "section", label: "Contact Information" },
//     { type: "text", label: "Full Name", key: "name", required: true },
//     { type: "email", label: "Email Address", key: "email" },
//     { type: "number", label: "Phone Number", key: "phone" },
//     { type: "section", label: "Plumbing Details" },
//     { type: "select", label: "Issue Type", key: "issueType", options: ["Leak", "Installation", "Maintenance", "Other"] },
//     { type: "textarea", label: "Additional Instructions", key: "details" },
//     { type: "date", label: "Preferred Service Date", key: "date" }
//   ]
// },
// {
//   id: "electrician",
//   slug: "electrician",
//   name: "Electrician",
//   category: "home-garden",
//   categoryLabel: "Home & Garden",
//   categoryBg: "bg-green-100",
//   pricingType: "fixed",
//   image: "https://images.unsplash.com/photo-1581092335083-cda48ef2c40e?auto=format&fit=crop&w=800&q=80",
//   description: "Professional electrician services for wiring, repairs, and installations.",
//   isActive: true,
//   isFeatured: true,
//   questions: [
//     { type: "section", label: "Contact Information" },
//     { type: "text", label: "Full Name", key: "name", required: true },
//     { type: "email", label: "Email Address", key: "email" },
//     { type: "number", label: "Phone Number", key: "phone" },
//     { type: "section", label: "Electrician Details" },
//     { type: "textarea", label: "Problem / Task Description", key: "details" },
//     { type: "select", label: "Type of Work", key: "workType", options: ["Wiring", "Repair", "Installation"] },
//     { type: "date", label: "Preferred Service Date", key: "date" }
//   ]
// },
// {
//   id: "house-cleaning",
//   slug: "house-cleaning",
//   name: "House Cleaning",
//   category: "home-garden",
//   categoryLabel: "Home & Garden",
//   categoryBg: "bg-green-100",
//   pricingType: "fixed",
//   image: "https://images.unsplash.com/photo-1581579180926-8e25f5fc6e9c?auto=format&fit=crop&w=800&q=80",
//   description: "Professional home cleaning services for residential properties.",
//   isActive: true,
//   isFeatured: true,
//   questions: [
//     { type: "section", label: "Contact Information" },
//     { type: "text", label: "Full Name", key: "name", required: true },
//     { type: "email", label: "Email Address", key: "email" },
//     { type: "number", label: "Phone Number", key: "phone" },
//     { type: "section", label: "Cleaning Details" },
//     { type: "select", label: "Cleaning Type", key: "cleaningType", options: ["Standard", "Deep Cleaning", "Move Out/In"] },
//     { type: "number", label: "Area (Sq Ft)", key: "area" },
//     { type: "textarea", label: "Additional Instructions", key: "details" },
//     { type: "date", label: "Preferred Service Date", key: "date" }
//   ]
// },
// {
//   id: "carpet-cleaning",
//   slug: "carpet-cleaning",
//   name: "Carpet Cleaning",
//   category: "home-garden",
//   categoryLabel: "Home & Garden",
//   categoryBg: "bg-green-100",
//   pricingType: "fixed",
//   image: "https://images.unsplash.com/photo-1581579180863-4d1d6d27d60b?auto=format&fit=crop&w=800&q=80",
//   description: "Professional carpet cleaning services for homes and offices.",
//   isActive: true,
//   isFeatured: true,
//   questions: [
//     { type: "section", label: "Contact Information" },
//     { type: "text", label: "Full Name", key: "name", required: true },
//     { type: "email", label: "Email Address", key: "email" },
//     { type: "number", label: "Phone Number", key: "phone" },
//     { type: "section", label: "Carpet Details" },
//     { type: "number", label: "Number of Carpets", key: "numCarpets" },
//     { type: "textarea", label: "Additional Instructions", key: "details" },
//     { type: "date", label: "Preferred Service Date", key: "date" }
//   ]
// },
// {
//   id: "window-cleaning",
//   slug: "window-cleaning",
//   name: "Window Cleaning",
//   category: "home-garden",
//   categoryLabel: "Home & Garden",
//   categoryBg: "bg-green-100",
//   pricingType: "fixed",
//   image: "https://images.unsplash.com/photo-1581579180943-5e4e3d2f4c71?auto=format&fit=crop&w=800&q=80",
//   description: "Professional window cleaning services for residential and commercial properties.",
//   isActive: true,
//   isFeatured: true,
//   questions: [
//     { type: "section", label: "Contact Information" },
//     { type: "text", label: "Full Name", key: "name", required: true },
//     { type: "email", label: "Email Address", key: "email" },
//     { type: "number", label: "Phone Number", key: "phone" },
//     { type: "section", label: "Window Details" },
//     { type: "number", label: "Number of Windows", key: "numWindows" },
//     { type: "textarea", label: "Additional Instructions", key: "details" },
//     { type: "date", label: "Preferred Service Date", key: "date" }
//   ]
// }

//   // ... similarly continue for Web Development, UI/UX Design, Digital Marketing, SEO Services, Content Writing, Copywriting, App Development, Photography, Video Editing, Podcast Editing, Live Streaming, Animation & Motion Graphics, Personal Trainer, Nutritionist Consultation, Yoga Instructor, Physiotherapy, Mental Health Coaching, Diet Meal Planning, Massage Therapy, Pilates Instruction, DJ Services, Makeup Artist, Dance Instructor, Martial Arts Training, Event Planning, Music Lessons, Voice Coaching, Party & Wedding Photography, Interior Styling, Personal Shopping
// ];


// export default serviceCategories;


export const serviceCategories = [
  {
    id: "house-cleaning",
    slug: "house-cleaning",
    name: "House Cleaning",
    category: "home-garden",
    categoryLabel: "Home & Garden",
    categoryBg: "bg-green-100",
    pricingType: "fixed",
    image: "https://images.pexels.com/photos/27176670/pexels-photo-27176670.jpeg",
    description: "Professional home cleaning services for residential properties.",
    isActive: true,
    isFeatured: true,
    questions: [
      { type: "section", label: "Contact Information" },
      { type: "text", label: "Full Name", key: "name", required: true },
      { type: "email", label: "Email Address", key: "email" },
      { type: "number", label: "Phone Number", key: "phone" },
      { type: "section", label: "Cleaning Details" },
      { type: "select", label: "Cleaning Type", key: "cleaningType", options: ["Standard", "Deep Cleaning", "Move Out/In"] },
      { type: "number", label: "Area (Sq Ft)", key: "area" },
      { type: "textarea", label: "Additional Instructions", key: "details" },
      { type: "date", label: "Preferred Service Date", key: "date" }
    ]
  },
  {
    id: "plumbing",
    slug: "plumbing",
    name: "Plumbing",
    category: "home-garden",
    categoryLabel: "Home & Garden",
    categoryBg: "bg-green-100",
    pricingType: "fixed",
image: "https://images.pexels.com/photos/8486972/pexels-photo-8486972.jpeg",
    description: "Professional plumbing services for repair, maintenance, and installation.",
    isActive: true,
    isFeatured: true,
    questions: [
      { type: "section", label: "Contact Information" },
      { type: "text", label: "Full Name", key: "name", required: true },
      { type: "email", label: "Email Address", key: "email" },
      { type: "number", label: "Phone Number", key: "phone" },
      { type: "section", label: "Plumbing Details" },
      { type: "select", label: "Issue Type", key: "issueType", options: ["Leak", "Installation", "Maintenance", "Other"] },
      { type: "textarea", label: "Additional Instructions", key: "details" },
      { type: "date", label: "Preferred Service Date", key: "date" }
    ]
  },
  {
    id: "electrician",
    slug: "electrician",
    name: "Electrician",
    category: "home-garden",
    categoryLabel: "Home & Garden",
    categoryBg: "bg-green-100",
    pricingType: "fixed",
    image: "https://images.pexels.com/photos/17842843/pexels-photo-17842843.jpeg",
    description: "Professional electrician services for wiring, repairs, and installations.",
    isActive: true,
    isFeatured: true,
    questions: [
      { type: "section", label: "Contact Information" },
      { type: "text", label: "Full Name", key: "name", required: true },
      { type: "email", label: "Email Address", key: "email" },
      { type: "number", label: "Phone Number", key: "phone" },
      { type: "section", label: "Electrician Details" },
      { type: "textarea", label: "Problem / Task Description", key: "details" },
      { type: "select", label: "Type of Work", key: "workType", options: ["Wiring", "Repair", "Installation"] },
      { type: "date", label: "Preferred Service Date", key: "date" }
    ]
  },
  {
    id: "ac-repair",
    slug: "ac-repair",
    name: "AC Repair",
    category: "home-garden",
    categoryLabel: "Home & Garden",
    categoryBg: "bg-green-100",
    pricingType: "fixed",
   image: "https://images.pexels.com/photos/5691622/pexels-photo-5691622.jpeg",
    description: "Professional AC repair and maintenance services for home and office.",
    isActive: true,
    isFeatured: true,
    questions: [
      { type: "section", label: "Contact Information" },
      { type: "text", label: "Full Name", key: "name", required: true },
      { type: "email", label: "Email Address", key: "email" },
      { type: "number", label: "Phone Number", key: "phone" },
      { type: "section", label: "AC Details" },
      { type: "text", label: "AC Brand / Model", key: "acModel" },
      { type: "select", label: "Issue Type", key: "issueType", options: ["Not Cooling", "Leakage", "Noise", "Other"] },
      { type: "textarea", label: "Additional Instructions", key: "details" },
      { type: "date", label: "Preferred Service Date", key: "date" }
    ]
  },
  {
    id: "roof-repair",
    slug: "roof-repair",
    name: "Roof Repair",
    category: "home-garden",
    categoryLabel: "Home & Garden",
    categoryBg: "bg-green-100",
    pricingType: "fixed",
    image: "https://images.pexels.com/photos/6474471/pexels-photo-6474471.jpeg",
    description: "Professional roof repair and maintenance for residential and commercial properties.",
    isActive: true,
    isFeatured: true,
    questions: [
      { type: "section", label: "Contact Information" },
      { type: "text", label: "Full Name", key: "name", required: true },
      { type: "email", label: "Email Address", key: "email" },
      { type: "number", label: "Phone Number", key: "phone" },
      { type: "section", label: "Roof Details" },
      { type: "select", label: "Roof Material", key: "roofMaterial", options: ["Tile", "Metal", "Shingle", "Other"] },
      { type: "textarea", label: "Issue Description / Instructions", key: "details" },
      { type: "date", label: "Preferred Service Date", key: "date" }
    ]
  },
  {
    id: "solar-panel-installation",
    slug: "solar-panel-installation",
    name: "Solar Panel Installation",
    category: "home-garden",
    categoryLabel: "Home & Garden",
    categoryBg: "bg-green-100",
    pricingType: "fixed",
   image: "https://images.pexels.com/photos/9875416/pexels-photo-9875416.jpeg",
    description: "Professional solar panel installation for homes and businesses.",
    isActive: true,
    isFeatured: true,
    questions: [
      { type: "section", label: "Contact Information" },
      { type: "text", label: "Full Name", key: "name", required: true },
      { type: "email", label: "Email Address", key: "email" },
      { type: "number", label: "Phone Number", key: "phone" },
      { type: "section", label: "Installation Details" },
      { type: "select", label: "Property Type", key: "propertyType", options: ["Residential", "Commercial"] },
      { type: "number", label: "Number of Panels", key: "numPanels" },
      { type: "textarea", label: "Additional Instructions", key: "details" },
      { type: "date", label: "Preferred Installation Date", key: "date" }
    ]
  },
  {
    id: "carpet-cleaning",
    slug: "carpet-cleaning",
    name: "Carpet Cleaning",
    category: "home-garden",
    categoryLabel: "Home & Garden",
    categoryBg: "bg-green-100",
    pricingType: "fixed",
   image: "https://images.pexels.com/photos/4239031/pexels-photo-4239031.jpeg",
    description: "Professional carpet cleaning services for homes and offices.",
    isActive: true,
    isFeatured: true,
    questions: [
      { type: "section", label: "Contact Information" },
      { type: "text", label: "Full Name", key: "name", required: true },
      { type: "email", label: "Email Address", key: "email" },
      { type: "number", label: "Phone Number", key: "phone" },
      { type: "section", label: "Carpet Details" },
      { type: "number", label: "Number of Carpets", key: "numCarpets" },
      { type: "textarea", label: "Additional Instructions", key: "details" },
      { type: "date", label: "Preferred Service Date", key: "date" }
    ]
  },
  {
    id: "window-cleaning",
    slug: "window-cleaning",
    name: "Window Cleaning",
    category: "home-garden",
    categoryLabel: "Home & Garden",
    categoryBg: "bg-green-100",
    pricingType: "fixed",
   image: "https://images.pexels.com/photos/4107125/pexels-photo-4107125.jpeg",
    description: "Professional window cleaning services for residential and commercial properties.",
    isActive: true,
    isFeatured: true,
    questions: [
      { type: "section", label: "Contact Information" },
      { type: "text", label: "Full Name", key: "name", required: true },
      { type: "email", label: "Email Address", key: "email" },
      { type: "number", label: "Phone Number", key: "phone" },
      { type: "section", label: "Window Details" },
      { type: "number", label: "Number of Windows", key: "numWindows" },
      { type: "textarea", label: "Additional Instructions", key: "details" },
      { type: "date", label: "Preferred Service Date", key: "date" }
    ]
  },
  {
    id: "graphic-design",
    slug: "graphic-design",
    name: "Graphic Design",
    category: "creative-digital",
    categoryLabel: "Creative & Digital",
    categoryBg: "bg-blue-100",
    pricingType: "fixed",
    image: "https://images.pexels.com/photos/196644/pexels-photo-196644.jpeg",
    description: "Professional graphic design services for logos, branding, and marketing materials.",
    isActive: true,
    isFeatured: true,
    questions: [
      { type: "section", label: "Contact Information" },
      { type: "text", label: "Full Name", key: "name", required: true },
      { type: "email", label: "Email Address", key: "email" },
      { type: "number", label: "Phone Number", key: "phone" },
      { type: "section", label: "Design Details" },
      { type: "text", label: "Project Type", key: "projectType", options: ["Logo", "Branding", "Flyer", "Other"] },
      { type: "textarea", label: "Project Description / Instructions", key: "details" },
      { type: "date", label: "Preferred Completion Date", key: "date" }
    ]
  },
  {
    id: "web-design",
    slug: "web-design",
    name: "Web Design",
    category: "creative-digital",
    categoryLabel: "Creative & Digital",
    categoryBg: "bg-blue-100",
    pricingType: "fixed",
    image: "https://images.pexels.com/photos/326503/pexels-photo-326503.jpeg",
    description: "Professional website design services with modern and responsive layouts.",
    isActive: true,
    isFeatured: true,
    questions: [
      { type: "section", label: "Contact Information" },
      { type: "text", label: "Full Name", key: "name", required: true },
      { type: "email", label: "Email Address", key: "email" },
      { type: "number", label: "Phone Number", key: "phone" },
      { type: "section", label: "Website Details" },
      { type: "text", label: "Website Type", key: "websiteType", options: ["Corporate", "E-commerce", "Portfolio", "Other"] },
      { type: "textarea", label: "Additional Requirements", key: "details" },
      { type: "date", label: "Preferred Launch Date", key: "date" }
    ]
  },
  {
    id: "web-development",
    slug: "web-development",
    name: "Web Development",
    category: "creative-digital",
    categoryLabel: "Creative & Digital",
    categoryBg: "bg-blue-100",
    pricingType: "fixed",
   image: "https://images.pexels.com/photos/1181271/pexels-photo-1181271.jpeg",
    description: "Professional web development services for modern and responsive websites.",
    isActive: true,
    isFeatured: true,
    questions: [
      { type: "section", label: "Contact Information" },
      { type: "text", label: "Full Name", key: "name", required: true },
      { type: "email", label: "Email Address", key: "email" },
      { type: "number", label: "Phone Number", key: "phone" },
      { type: "section", label: "Development Details" },
      { type: "select", label: "Preferred Platform", key: "platform", options: ["WordPress", "Custom Code", "Shopify", "Other"] },
      { type: "textarea", label: "Project Requirements / Instructions", key: "details" },
      { type: "date", label: "Preferred Completion Date", key: "date" }
    ]
  },
  {
    id: "ui-ux-design",
    slug: "ui-ux-design",
    name: "UI/UX Design",
    category: "creative-digital",
    categoryLabel: "Creative & Digital",
    categoryBg: "bg-blue-100",
    pricingType: "fixed",
   image: "https://images.pexels.com/photos/196645/pexels-photo-196645.jpeg",
    description: "Professional UI/UX design services to improve user experience and interfaces.",
    isActive: true,
    isFeatured: true,
    questions: [
      { type: "section", label: "Contact Information" },
      { type: "text", label: "Full Name", key: "name", required: true },
      { type: "email", label: "Email Address", key: "email" },
      { type: "number", label: "Phone Number", key: "phone" },
      { type: "section", label: "Design Details" },
      { type: "text", label: "Project Scope", key: "projectScope" },
      { type: "textarea", label: "Requirements / Notes", key: "details" },
      { type: "date", label: "Preferred Completion Date", key: "date" }
    ]
  },
  {
    id: "digital-marketing",
    slug: "digital-marketing",
    name: "Digital Marketing",
    category: "creative-digital",
    categoryLabel: "Creative & Digital",
    categoryBg: "bg-blue-100",
    pricingType: "fixed",
   image: "https://images.pexels.com/photos/905163/pexels-photo-905163.jpeg",
    description: "Professional digital marketing services to grow your online presence and leads.",
    isActive: true,
    isFeatured: true,
    questions: [
      { type: "section", label: "Contact Information" },
      { type: "text", label: "Full Name", key: "name", required: true },
      { type: "email", label: "Email Address", key: "email" },
      { type: "number", label: "Phone Number", key: "phone" },
      { type: "section", label: "Marketing Details" },
      { type: "select", label: "Service Focus", key: "serviceFocus", options: ["SEO", "Social Media", "Ads", "Content Marketing"] },
      { type: "textarea", label: "Campaign Goals / Instructions", key: "details" },
      { type: "date", label: "Preferred Start Date", key: "date" }
    ]
  },
  {
    id: "seo-services",
  slug: "seo-services",
  name: "SEO Services",
  category: "creative-digital",
  categoryLabel: "Creative & Digital",
  categoryBg: "bg-blue-100",
  pricingType: "fixed",
  image: "https://images.pexels.com/photos/13628541/pexels-photo-13628541.jpeg",
  description: "Search engine optimization to improve website visibility and ranking.",
  isActive: true,
  isFeatured: true,
  questions: [
    { type: "section", label: "Contact Information" },
    { type: "text", label: "Full Name", key: "name", required: true },
    { type: "email", label: "Email Address", key: "email" },
    { type: "number", label: "Phone Number", key: "phone" },
    { type: "section", label: "SEO Details" },
    { type: "textarea", label: "Website URL", key: "websiteUrl" },
    { type: "textarea", label: "Keywords / Goals", key: "keywords" },
    { type: "date", label: "Preferred Start Date", key: "date" }
  ]
},

  {
    id: "personal-trainer",
    slug: "personal-trainer",
    name: "Personal Trainer",
    category: "health-wellness",
    categoryLabel: "Health & Wellness",
    categoryBg: "bg-red-100",
    pricingType: "fixed",
   image: "https://images.pexels.com/photos/841130/pexels-photo-841130.jpeg",
    description: "Professional personal training services for fitness and strength goals.",
    isActive: true,
    isFeatured: true,
    questions: [
      { type: "section", label: "Contact Information" },
      { type: "text", label: "Full Name", key: "name", required: true },
      { type: "email", label: "Email Address", key: "email" },
      { type: "number", label: "Phone Number", key: "phone" },
      { type: "section", label: "Fitness Goals" },
      { type: "select", label: "Goal Type", key: "goalType", options: ["Weight Loss", "Muscle Gain", "Flexibility", "General Fitness"] },
      { type: "textarea", label: "Additional Notes / Injuries", key: "details" },
      { type: "date", label: "Preferred Start Date", key: "date" }
    ]
  },
  {
    id: "nutritionist-consultation",
    slug: "nutritionist-consultation",
    name: "Nutritionist Consultation",
    category: "health-wellness",
    categoryLabel: "Health & Wellness",
    categoryBg: "bg-red-100",
    pricingType: "fixed",
  image: "https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg",
    description: "Professional nutritionist consultation to plan your diet and wellness.",
    isActive: true,
    isFeatured: true,
    questions: [
      { type: "section", label: "Contact Information" },
      { type: "text", label: "Full Name", key: "name", required: true },
      { type: "email", label: "Email Address", key: "email" },
      { type: "number", label: "Phone Number", key: "phone" },
      { type: "section", label: "Dietary Preferences" },
      { type: "textarea", label: "Current Diet / Goals", key: "dietGoals" },
      { type: "textarea", label: "Additional Notes / Allergies", key: "details" },
      { type: "date", label: "Preferred Consultation Date", key: "date" }
    ]
  },
  {
    id: "yoga-instructor",
    slug: "yoga-instructor",
    name: "Yoga Instructor",
    category: "health-wellness",
    categoryLabel: "Health & Wellness",
    categoryBg: "bg-red-100",
    pricingType: "fixed",
  image: "https://images.pexels.com/photos/3822622/pexels-photo-3822622.jpeg",
    description: "Professional yoga instruction for all levels to improve flexibility and wellness.",
    isActive: true,
    isFeatured: true,
    questions: [
      { type: "section", label: "Contact Information" },
      { type: "text", label: "Full Name", key: "name", required: true },
      { type: "email", label: "Email Address", key: "email" },
      { type: "number", label: "Phone Number", key: "phone" },
      { type: "section", label: "Yoga Details" },
      { type: "select", label: "Experience Level", key: "level", options: ["Beginner", "Intermediate", "Advanced"] },
      { type: "textarea", label: "Goals / Health Notes", key: "details" },
      { type: "date", label: "Preferred Session Date", key: "date" }
    ]
  },
  {
    id: "physiotherapy",
    slug: "physiotherapy",
    name: "Physiotherapy",
    category: "health-wellness",
    categoryLabel: "Health & Wellness",
    categoryBg: "bg-red-100",
    pricingType: "fixed",
  image: "https://images.pexels.com/photos/4506105/pexels-photo-4506105.jpeg",
    description: "Professional physiotherapy services to aid recovery and improve mobility.",
    isActive: true,
    isFeatured: true,
    questions: [
      { type: "section", label: "Contact Information" },
      { type: "text", label: "Full Name", key: "name", required: true },
      { type: "email", label: "Email Address", key: "email" },
      { type: "number", label: "Phone Number", key: "phone" },
      { type: "section", label: "Physiotherapy Details" },
      { type: "textarea", label: "Condition / Injuries", key: "condition" },
      { type: "textarea", label: "Additional Notes", key: "details" },
      { type: "date", label: "Preferred Appointment Date", key: "date" }
    ]
  },
  {
    id: "mental-health-coaching",
    slug: "mental-health-coaching",
    name: "Mental Health Coaching",
    category: "health-wellness",
    categoryLabel: "Health & Wellness",
    categoryBg: "bg-red-100",
    pricingType: "fixed",
   image: "https://images.pexels.com/photos/7176319/pexels-photo-7176319.jpeg",
    description: "Professional mental health coaching to improve well-being and manage stress.",
    isActive: true,
    isFeatured: true,
    questions: [
      { type: "section", label: "Contact Information" },
      { type: "text", label: "Full Name", key: "name", required: true },
      { type: "email", label: "Email Address", key: "email" },
      { type: "number", label: "Phone Number", key: "phone" },
      { type: "section", label: "Coaching Details" },
      { type: "textarea", label: "Concerns / Goals", key: "goals" },
      { type: "textarea", label: "Additional Notes", key: "details" },
      { type: "date", label: "Preferred Session Date", key: "date" }
    ]
  },
  {
    id: "diet-meal-planning",
    slug: "diet-meal-planning",
    name: "Diet Meal Planning",
    category: "health-wellness",
    categoryLabel: "Health & Wellness",
    categoryBg: "bg-red-100",
    pricingType: "fixed",
    image: "https://images.pexels.com/photos/1640774/pexels-photo-1640774.jpeg",
    description: "Professional diet meal planning services to help achieve your nutrition goals.",
    isActive: true,
    isFeatured: true,
    questions: [
      { type: "section", label: "Contact Information" },
      { type: "text", label: "Full Name", key: "name", required: true },
      { type: "email", label: "Email Address", key: "email" },
      { type: "number", label: "Phone Number", key: "phone" },
      { type: "section", label: "Diet Details" },
      { type: "textarea", label: "Current Diet / Preferences", key: "diet" },
      { type: "textarea", label: "Additional Notes / Allergies", key: "details" },
      { type: "date", label: "Preferred Start Date", key: "date" }
    ]
  },
  {
    id: "massage-therapy",
    slug: "massage-therapy",
    name: "Massage Therapy",
    category: "health-wellness",
    categoryLabel: "Health & Wellness",
    categoryBg: "bg-red-100",
    pricingType: "fixed",
   image: "https://images.pexels.com/photos/3757942/pexels-photo-3757942.jpeg",
    description: "Professional massage therapy to relax muscles and reduce stress.",
    isActive: true,
    isFeatured: true,
    questions: [
      { type: "section", label: "Contact Information" },
      { type: "text", label: "Full Name", key: "name", required: true },
      { type: "email", label: "Email Address", key: "email" },
      { type: "number", label: "Phone Number", key: "phone" },
      { type: "section", label: "Massage Details" },
      { type: "select", label: "Massage Type", key: "massageType", options: ["Swedish", "Deep Tissue", "Sports", "Other"] },
      { type: "textarea", label: "Additional Notes", key: "details" },
      { type: "date", label: "Preferred Appointment Date", key: "date" }
    ]
  },
  {
    id: "pilates-instruction",
    slug: "pilates-instruction",
    name: "Pilates Instruction",
    category: "health-wellness",
    categoryLabel: "Health & Wellness",
    categoryBg: "bg-red-100",
    pricingType: "fixed",
   image: "https://images.pexels.com/photos/4662438/pexels-photo-4662438.jpeg",
    description: "Professional Pilates instruction to improve core strength and flexibility.",
    isActive: true,
    isFeatured: true,
    questions: [
      { type: "section", label: "Contact Information" },
      { type: "text", label: "Full Name", key: "name", required: true },
      { type: "email", label: "Email Address", key: "email" },
      { type: "number", label: "Phone Number", key: "phone" },
      { type: "section", label: "Pilates Details" },
      { type: "select", label: "Experience Level", key: "level", options: ["Beginner", "Intermediate", "Advanced"] },
      { type: "textarea", label: "Goals / Notes", key: "details" },
      { type: "date", label: "Preferred Session Date", key: "date" }
    ]
  },

  {
    id: "dj-services",
    slug: "dj-services",
    name: "DJ Services",
    category: "entertainment-lifestyle",
    categoryLabel: "Entertainment & Lifestyle",
    categoryBg: "bg-purple-100",
    pricingType: "fixed",
    image: "https://images.pexels.com/photos/1540406/pexels-photo-1540406.jpeg",
    description: "Professional DJ services for parties, events, and weddings.",
    isActive: true,
    isFeatured: true,
    questions: [
      { type: "section", label: "Contact Information" },
      { type: "text", label: "Full Name", key: "name", required: true },
      { type: "email", label: "Email Address", key: "email" },
      { type: "number", label: "Phone Number", key: "phone" },
      { type: "section", label: "Event Details" },
      { type: "text", label: "Event Type", key: "eventType" },
      { type: "number", label: "Event Duration (Hours)", key: "duration" },
      { type: "textarea", label: "Additional Notes / Playlist Requests", key: "details" },
      { type: "date", label: "Event Date", key: "date" }
    ]
  },
  {
    id: "makeup-artist",
    slug: "makeup-artist",
    name: "Makeup Artist",
    category: "entertainment-lifestyle",
    categoryLabel: "Entertainment & Lifestyle",
    categoryBg: "bg-purple-100",
    pricingType: "fixed",
    image: "https://images.pexels.com/photos/2113855/pexels-photo-2113855.jpeg",
    description: "Professional makeup artist services for weddings, events, and photoshoots.",
    isActive: true,
    isFeatured: true,
    questions: [
      { type: "section", label: "Contact Information" },
      { type: "text", label: "Full Name", key: "name", required: true },
      { type: "email", label: "Email Address", key: "email" },
      { type: "number", label: "Phone Number", key: "phone" },
      { type: "section", label: "Makeup Details" },
      { type: "text", label: "Occasion", key: "occasion" },
      { type: "textarea", label: "Style / Preferences", key: "details" },
      { type: "date", label: "Event Date", key: "date" }
    ]
  },
  {
    id: "dance-instructor",
    slug: "dance-instructor",
    name: "Dance Instructor",
    category: "entertainment-lifestyle",
    categoryLabel: "Entertainment & Lifestyle",
    categoryBg: "bg-purple-100",
    pricingType: "fixed",
   image: "https://images.pexels.com/photos/5888334/pexels-photo-5888334.jpeg",
    description: "Professional dance instructor services for private lessons or group classes.",
    isActive: true,
    isFeatured: true,
    questions: [
      { type: "section", label: "Contact Information" },
      { type: "text", label: "Full Name", key: "name", required: true },
      { type: "email", label: "Email Address", key: "email" },
      { type: "number", label: "Phone Number", key: "phone" },
      { type: "section", label: "Dance Details" },
      { type: "select", label: "Dance Style", key: "danceStyle", options: ["Ballet", "Hip Hop", "Salsa", "Contemporary", "Other"] },
      { type: "textarea", label: "Experience / Goals", key: "details" },
      { type: "date", label: "Preferred Lesson Date", key: "date" }
    ]
  },
  {
    id: "martial-arts-training",
    slug: "martial-arts-training",
    name: "Martial Arts Training",
    category: "entertainment-lifestyle",
    categoryLabel: "Entertainment & Lifestyle",
    categoryBg: "bg-purple-100",
    pricingType: "fixed",
   image: "https://images.pexels.com/photos/6296037/pexels-photo-6296037.jpeg",
    description: "Professional martial arts training for self-defense and fitness.",
    isActive: true,
    isFeatured: true,
    questions: [
      { type: "section", label: "Contact Information" },
      { type: "text", label: "Full Name", key: "name", required: true },
      { type: "email", label: "Email Address", key: "email" },
      { type: "number", label: "Phone Number", key: "phone" },
      { type: "section", label: "Training Details" },
      { type: "select", label: "Martial Arts Style", key: "style", options: ["Karate", "Taekwondo", "Judo", "Kung Fu", "Other"] },
      { type: "textarea", label: "Experience / Goals", key: "details" },
      { type: "date", label: "Preferred Training Date", key: "date" }
    ]
  },
  {
    id: "event-planning",
    slug: "event-planning",
    name: "Event Planning",
    category: "entertainment-lifestyle",
    categoryLabel: "Entertainment & Lifestyle",
    categoryBg: "bg-purple-100",
    pricingType: "fixed",
   image: "https://images.pexels.com/photos/587741/pexels-photo-587741.jpeg",
    description: "Professional event planning services for parties, weddings, and corporate events.",
    isActive: true,
    isFeatured: true,
    questions: [
      { type: "section", label: "Contact Information" },
      { type: "text", label: "Full Name", key: "name", required: true },
      { type: "email", label: "Email Address", key: "email" },
      { type: "number", label: "Phone Number", key: "phone" },
      { type: "section", label: "Event Details" },
      { type: "text", label: "Event Type", key: "eventType" },
      { type: "number", label: "Number of Guests", key: "guests" },
      { type: "textarea", label: "Additional Instructions", key: "details" },
      { type: "date", label: "Event Date", key: "date" }
    ]
  },
  {
    id: "music-lessons",
    slug: "music-lessons",
    name: "Music Lessons",
    category: "entertainment-lifestyle",
    categoryLabel: "Entertainment & Lifestyle",
    categoryBg: "bg-purple-100",
    pricingType: "fixed",
   image: "https://images.pexels.com/photos/164821/pexels-photo-164821.jpeg",
    description: "Professional music lessons for various instruments and skill levels.",
    isActive: true,
    isFeatured: true,
    questions: [
      { type: "section", label: "Contact Information" },
      { type: "text", label: "Full Name", key: "name", required: true },
      { type: "email", label: "Email Address", key: "email" },
      { type: "number", label: "Phone Number", key: "phone" },
      { type: "section", label: "Lesson Details" },
      { type: "select", label: "Instrument", key: "instrument", options: ["Guitar", "Piano", "Violin", "Drums", "Other"] },
      { type: "textarea", label: "Skill Level / Goals", key: "details" },
      { type: "date", label: "Preferred Lesson Date", key: "date" }
    ]
  },
  {
    id: "voice-coaching",
    slug: "voice-coaching",
    name: "Voice Coaching",
    category: "entertainment-lifestyle",
    categoryLabel: "Entertainment & Lifestyle",
    categoryBg: "bg-purple-100",
    pricingType: "fixed",
    image: "https://images.pexels.com/photos/7521312/pexels-photo-7521312.jpeg",
    description: "Professional voice coaching to improve singing or speaking skills.",
    isActive: true,
    isFeatured: true,
    questions: [
      { type: "section", label: "Contact Information" },
      { type: "text", label: "Full Name", key: "name", required: true },
      { type: "email", label: "Email Address", key: "email" },
      { type: "number", label: "Phone Number", key: "phone" },
      { type: "section", label: "Coaching Details" },
      { type: "select", label: "Focus Area", key: "focusArea", options: ["Singing", "Public Speaking", "Other"] },
      { type: "textarea", label: "Goals / Notes", key: "details" },
      { type: "date", label: "Preferred Session Date", key: "date" }
    ]
  },
  {
    id: "party-wedding-photography",
    slug: "party-wedding-photography",
    name: "Party & Wedding Photography",
    category: "entertainment-lifestyle",
    categoryLabel: "Entertainment & Lifestyle",
    categoryBg: "bg-purple-100",
    pricingType: "fixed",
    image: "https://images.pexels.com/photos/2959192/pexels-photo-2959192.jpeg",
    description: "Professional photography services for parties, weddings, and special events.",
    isActive: true,
    isFeatured: true,
    questions: [
      { type: "section", label: "Contact Information" },
      { type: "text", label: "Full Name", key: "name", required: true },
      { type: "email", label: "Email Address", key: "email" },
      { type: "number", label: "Phone Number", key: "phone" },
      { type: "section", label: "Photography Details" },
      { type: "text", label: "Event Type", key: "eventType" },
      { type: "number", label: "Number of Guests / Photos", key: "guests" },
      { type: "textarea", label: "Style / Notes", key: "details" },
      { type: "date", label: "Event Date", key: "date" }
    ]
  },
  {
    id: "interior-styling",
    slug: "interior-styling",
    name: "Interior Styling",
    category: "entertainment-lifestyle",
    categoryLabel: "Entertainment & Lifestyle",
    categoryBg: "bg-purple-100",
    pricingType: "fixed",
   image: "https://images.pexels.com/photos/1571460/pexels-photo-1571460.jpeg",
    description: "Professional interior styling services to beautify your living or working space.",
    isActive: true,
    isFeatured: true,
    questions: [
      { type: "section", label: "Contact Information" },
      { type: "text", label: "Full Name", key: "name", required: true },
      { type: "email", label: "Email Address", key: "email" },
      { type: "number", label: "Phone Number", key: "phone" },
      { type: "section", label: "Styling Details" },
      { type: "textarea", label: "Room / Space Details", key: "details" },
      { type: "date", label: "Preferred Styling Date", key: "date" }
    ]
  },
  {
    id: "personal-shopping",
    slug: "personal-shopping",
    name: "Personal Shopping",
    category: "entertainment-lifestyle",
    categoryLabel: "Entertainment & Lifestyle",
    categoryBg: "bg-purple-100",
    pricingType: "fixed",
   image: "https://images.pexels.com/photos/974911/pexels-photo-974911.jpeg",
    description: "Professional personal shopping services to assist with purchases and style.",
    isActive: true,
    isFeatured: true,
    questions: [
      { type: "section", label: "Contact Information" },
      { type: "text", label: "Full Name", key: "name", required: true },
      { type: "email", label: "Email Address", key: "email" },
      { type: "number", label: "Phone Number", key: "phone" },
      { type: "section", label: "Shopping Details" },
      { type: "textarea", label: "Items / Preferences", key: "details" },
      { type: "date", label: "Preferred Shopping Date", key: "date" }
    ]
  },
  {
  id: "bathroom-renovation",
  slug: "bathroom-renovation",
  name: "Bathroom Renovation",
  category: "home-garden",
  categoryLabel: "Home & Garden",
  categoryBg: "bg-green-100",
  pricingType: "fixed",
  image: "https://images.pexels.com/photos/7031408/pexels-photo-7031408.jpeg",
  description: "Professional bathroom renovation services for modern and stylish spaces.",
  isActive: true,
  isFeatured: true,
  questions: [
    { type: "section", label: "Contact Information" },
    { type: "text", label: "Full Name", key: "name", required: true },
    { type: "email", label: "Email Address", key: "email" },
    { type: "number", label: "Phone Number", key: "phone" },
    { type: "section", label: "Renovation Details" },
    { type: "select", label: "Bathroom Type", key: "bathroomType", options: ["Small", "Medium", "Large"] },
    { type: "textarea", label: "Requirements / Notes", key: "details" },
    { type: "date", label: "Preferred Renovation Date", key: "date" }
  ]
},

{
  id: "kitchen-renovation",
  slug: "kitchen-renovation",
  name: "Kitchen Renovation",
  category: "home-garden",
  categoryLabel: "Home & Garden",
  categoryBg: "bg-green-100",
  pricingType: "fixed",
  image: "https://images.pexels.com/photos/5824519/pexels-photo-5824519.jpeg",
  description: "Professional kitchen renovation services for modern and functional kitchens.",
  isActive: true,
  isFeatured: true,
  questions: [
    { type: "section", label: "Contact Information" },
    { type: "text", label: "Full Name", key: "name", required: true },
    { type: "email", label: "Email Address", key: "email" },
    { type: "number", label: "Phone Number", key: "phone" },
    { type: "section", label: "Kitchen Details" },
    { type: "select", label: "Kitchen Size", key: "kitchenSize", options: ["Small", "Medium", "Large"] },
    { type: "textarea", label: "Requirements / Notes", key: "details" },
    { type: "date", label: "Preferred Renovation Date", key: "date" }
  ]
},

{
  id: "pest-control",
  slug: "pest-control",
  name: "Pest Control",
  category: "home-garden",
  categoryLabel: "Home & Garden",
  categoryBg: "bg-green-100",
  pricingType: "fixed",
  image: "https://images.pexels.com/photos/6197120/pexels-photo-6197120.jpeg",
  description: "Professional pest control services for homes and commercial spaces.",
  isActive: true,
  isFeatured: true,
  questions: [
    { type: "section", label: "Contact Information" },
    { type: "text", label: "Full Name", key: "name", required: true },
    { type: "email", label: "Email Address", key: "email" },
    { type: "number", label: "Phone Number", key: "phone" },
    { type: "section", label: "Pest Details" },
    { type: "select", label: "Pest Type", key: "pestType", options: ["Cockroaches", "Termites", "Rodents", "Other"] },
    { type: "textarea", label: "Additional Details", key: "details" },
    { type: "date", label: "Preferred Service Date", key: "date" }
  ]
},

{
  id: "painting-services",
  slug: "painting-services",
  name: "Painting Services",
  category: "home-garden",
  categoryLabel: "Home & Garden",
  categoryBg: "bg-green-100",
  pricingType: "fixed",
  image: "https://images.pexels.com/photos/6474342/pexels-photo-6474342.jpeg",
  description: "Professional painting services for homes, offices, and commercial spaces.",
  isActive: true,
  isFeatured: true,
  questions: [
    { type: "section", label: "Contact Information" },
    { type: "text", label: "Full Name", key: "name", required: true },
    { type: "email", label: "Email Address", key: "email" },
    { type: "number", label: "Phone Number", key: "phone" },
    { type: "section", label: "Painting Details" },
    { type: "select", label: "Painting Type", key: "paintingType", options: ["Interior", "Exterior", "Full Property"] },
    { type: "textarea", label: "Color Preferences / Notes", key: "details" },
    { type: "date", label: "Preferred Service Date", key: "date" }
  ]
},

{
  id: "furniture-assembly",
  slug: "furniture-assembly",
  name: "Furniture Assembly",
  category: "home-garden",
  categoryLabel: "Home & Garden",
  categoryBg: "bg-green-100",
  pricingType: "fixed",
  image: "https://images.pexels.com/photos/5691613/pexels-photo-5691613.jpeg",
  description: "Professional furniture assembly services for homes and offices.",
  isActive: true,
  isFeatured: true,
  questions: [
    { type: "section", label: "Contact Information" },
    { type: "text", label: "Full Name", key: "name", required: true },
    { type: "email", label: "Email Address", key: "email" },
    { type: "number", label: "Phone Number", key: "phone" },
    { type: "section", label: "Furniture Details" },
    { type: "text", label: "Furniture Type", key: "furnitureType" },
    { type: "textarea", label: "Assembly Instructions / Notes", key: "details" },
    { type: "date", label: "Preferred Assembly Date", key: "date" }
  ]
},

{
  id: "laundry-service",
  slug: "laundry-service",
  name: "Laundry Service",
  category: "home-garden",
  categoryLabel: "Home & Garden",
  categoryBg: "bg-green-100",
  pricingType: "fixed",
  image: "https://images.pexels.com/photos/5591834/pexels-photo-5591834.jpeg",
  description: "Professional laundry and dry cleaning services with pickup and delivery.",
  isActive: true,
  isFeatured: true,
  questions: [
    { type: "section", label: "Contact Information" },
    { type: "text", label: "Full Name", key: "name", required: true },
    { type: "email", label: "Email Address", key: "email" },
    { type: "number", label: "Phone Number", key: "phone" },
    { type: "section", label: "Laundry Details" },
    { type: "number", label: "Number of Clothes", key: "clothesCount" },
    { type: "textarea", label: "Special Instructions", key: "details" },
    { type: "date", label: "Preferred Pickup Date", key: "date" }
  ]
},

{
  id: "moving-service",
  slug: "moving-service",
  name: "Moving Service",
  category: "home-garden",
  categoryLabel: "Home & Garden",
  categoryBg: "bg-green-100",
  pricingType: "fixed",
  image: "https://images.pexels.com/photos/4246120/pexels-photo-4246120.jpeg",
  description: "Professional moving and shifting services for homes and offices.",
  isActive: true,
  isFeatured: true,
  questions: [
    { type: "section", label: "Contact Information" },
    { type: "text", label: "Full Name", key: "name", required: true },
    { type: "email", label: "Email Address", key: "email" },
    { type: "number", label: "Phone Number", key: "phone" },
    { type: "section", label: "Moving Details" },
    { type: "text", label: "Pickup Location", key: "pickup" },
    { type: "text", label: "Drop-off Location", key: "dropoff" },
    { type: "textarea", label: "Additional Notes", key: "details" },
    { type: "date", label: "Moving Date", key: "date" }
  ]
},

{
  id: "garden-landscaping",
  slug: "garden-landscaping",
  name: "Garden Landscaping",
  category: "home-garden",
  categoryLabel: "Home & Garden",
  categoryBg: "bg-green-100",
  pricingType: "fixed",
  image: "https://images.pexels.com/photos/32759035/pexels-photo-32759035.jpeg",
  description: "Professional garden landscaping services to beautify outdoor spaces.",
  isActive: true,
  isFeatured: true,
  questions: [
    { type: "section", label: "Contact Information" },
    { type: "text", label: "Full Name", key: "name", required: true },
    { type: "email", label: "Email Address", key: "email" },
    { type: "number", label: "Phone Number", key: "phone" },
    { type: "section", label: "Landscaping Details" },
    { type: "textarea", label: "Garden Requirements / Ideas", key: "details" },
    { type: "date", label: "Preferred Service Date", key: "date" }
  ]
},

{
  id: "lawn-mowing",
  slug: "lawn-mowing",
  name: "Lawn Mowing",
  category: "home-garden",
  categoryLabel: "Home & Garden",
  categoryBg: "bg-green-100",
  pricingType: "fixed",
  image: "https://images.pexels.com/photos/6728919/pexels-photo-6728919.jpeg",
  description: "Professional lawn mowing and grass maintenance services.",
  isActive: true,
  isFeatured: true,
  questions: [
    { type: "section", label: "Contact Information" },
    { type: "text", label: "Full Name", key: "name", required: true },
    { type: "email", label: "Email Address", key: "email" },
    { type: "number", label: "Phone Number", key: "phone" },
    { type: "section", label: "Lawn Details" },
    { type: "number", label: "Lawn Size (Sq Ft)", key: "lawnSize" },
    { type: "textarea", label: "Additional Instructions", key: "details" },
    { type: "date", label: "Preferred Service Date", key: "date" }
  ]
},

{
  id: "pool-maintenance",
  slug: "pool-maintenance",
  name: "Pool Maintenance",
  category: "home-garden",
  categoryLabel: "Home & Garden",
  categoryBg: "bg-green-100",
  pricingType: "fixed",
  image: "https://images.pexels.com/photos/261327/pexels-photo-261327.jpeg",
  description: "Professional pool cleaning and maintenance services for residential and commercial pools.",
  isActive: true,
  isFeatured: true,
  questions: [
    { type: "section", label: "Contact Information" },
    { type: "text", label: "Full Name", key: "name", required: true },
    { type: "email", label: "Email Address", key: "email" },
    { type: "number", label: "Phone Number", key: "phone" },
    { type: "section", label: "Pool Details" },
    { type: "select", label: "Pool Type", key: "poolType", options: ["Indoor", "Outdoor", "Commercial"] },
    { type: "textarea", label: "Maintenance Requirements", key: "details" },
    { type: "date", label: "Preferred Service Date", key: "date" }
  ]
}


  // Continue same structure for remaining services (Bathroom Renovation, Kitchen Renovation, Pest Control, Painting Services, Furniture Assembly, Laundry Service, Moving Service, Garden Landscaping, Lawn Mowing, Pool Maintenance)
];

export default serviceCategories;